### ISSUE TITLE
Failed to convert map to Mac navmesh format. FIXED*

### ISSUE THREAD

**Issue by umkarlo** [InvoxiPlayGames/BO3MacFix#19]
I successfully downloaded BO3macfix, but whenever I try to open a custom map from the workshop I get the navmesh error.
I have read about a fix but no actual guide on how to do it. 

Could anyone guide me on how to get this fixed? Thanks!
<img width="1726" alt="Screenshot 2024-09-22 at 11 00 15 a m" src="https://github.com/user-attachments/assets/4a93c925-56b0-45c6-97e9-adac002f3d3f">

**Comment by qtSlinky** [comment]
currently having the same issue

**Comment by umkarlo** [comment]
> currently having the same issue

I got it to work.. I had to install wine-stable through homebrew, which might be easier said than done, although it isn't too hard.

Just search for "homebrew" on google, go to the link follow instructions and install, then search for "wine-stable" on google and do the same, follow instructions and install through homebrew. 

It might tell you you need to download Rosetta since its a core-1 program, if you're using m1+.
You do not need to download it, I was able to run it on my m1 mac without having to install Rosetta. 

Most all maps are running perfect, only thing that does not show properly is the map preview picture, it just shows black..

Hope that helps! Lmk if it did so I can feel good about myself :p

**Comment by qtSlinky** [comment]
I've tried installing Wine-stable through several ways. (Including Homebrew's website) but it doesn't seem to install correctly and the maps still won't work. Running on an Air, M3

**Comment by umkarlo** [comment]
> I've tried installing Wine-stable through several ways. (Including Homebrew's website) but it doesn't seem to install correctly and the maps still won't work. Running on an Air, M3

does wine appear in your apps? If not then, like you said, it might have not installed properly. 

I was having issues with homebrew installing correctly, after downloading homebrew through the terminal, there are some specific instructions that you need to follow to add it to the directory or some ish like that..
Did you follow those instructions? If not, you can just do the homebrew install again, even if its already installed, and just follow the instructions it gives you at the end.

**Comment by qtSlinky** [comment]
I fixed the custom map loading issue. I can now get into a game and play the map. BUT !!!!! zombies aren't really moving (active) they stand still the entire time... Fixed issue #1, now gotta fix 2....any ideas?

**Comment by InvoxiPlayGames** [comment]
> zombies aren't really moving (active) they stand still the entire time... 

Which map is this? This is usually the result of a failed/improper conversion. Do other maps work?

**Comment by RINNECODER** [comment]
> I fixed the custom map loading issue. I can now get into a game and play the map. BUT !!!!! zombies aren't really moving (active) they stand still the entire time... Fixed issue #1, now gotta fix 2....any ideas?

How did u fixed the loading issue? I downloaded wine-stable and xquartz through homebrew and the app does show and work. I tried restarting and redownloading but I still have the "Failed to convert map to Mac navmesh format" issue.

**Comment by mustafa575775** [comment]
i have the Failed to convert map to Mac navmesh format and i looked at this whole page but i stil have the problem can someone tell me how to fix it

**Comment by SquidMonkey16** [comment]
> i have the Failed to convert map to Mac navmesh format and i looked at this whole page but i stil have the problem can someone tell me how to fix it

[This](https://github.com/InvoxiPlayGames/BO3MacFix/issues/36#issuecomment-2620487615) fixed the problem.

**Comment by InvoxiPlayGames** [comment]
Issues with this when using Wine 10.0 or with Wine installed via other sources should be fixed with 1.2-beta1. Please re-open or leave a comment if you're still running into the issues.
